name: Docker CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: docker build -t my-docker-app .

      - name: Save Docker Image
        run: docker save my-docker-app -o my-docker-app.tar

      - name: Upload Docker Image 
        uses: actions/upload-artifact@v3
        with:
          name: docker-image
          path: my-docker-app.tar 
          retention-days: 1

  push:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download Docker Image
        uses: actions/download-artifact@v3
        with:
          name: docker-image

      - name: Load Docker Image
        run: docker load -i my-docker-app.tar

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker Image
        run: |
          docker tag my-docker-app ${{ secrets.DOCKER_USERNAME }}/my-docker-app:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/my-docker-app:latest